### PR TITLE
Specifying dependencies that need to be installed to build this project

### PR DESCRIPTION
**Pull request by artrs-prog**
Should be useful for new contributors.

### CODE REVIEW

**Comment by Jake-Shadle** [comment]
Uhm, that's weird, what fails to build if you don't have OpenSSL installed? We shouldn't have any openssl dependencies in this project.

**Comment by artrs-prog** [comment]
@lsjostro It was [openssl-sys](https://crates.io/crates/openssl-sys).

**Comment by Jake-Shadle** [comment]
Ok, I'm still confused then, `openssl-sys` isn't part of our dependency graph.

**Comment by artrs-prog** [comment]
Ok, sorry for the confusion! I was building cargo-license-hound instead. Good that you caught this, could've confused some people. Disregard this PR :)

**Comment by Jake-Shadle** [comment]
Haha ok, yes, that makes more sense, I had the same problem when I tried to build it locally to see what its output looked like. :wink:

**Pull request closed without merging**
