### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by repi**
Just ran `cargo update` to update the lockfile to the latest dependencies.

```
    Updating aho-corasick v0.7.3 -> v0.7.6
    Removing argon2rs v0.2.5
      Adding arrayref v0.3.5
    Updating arrayvec v0.4.10 -> v0.4.11
    Updating atty v0.2.11 -> v0.2.13
    Updating autocfg v0.1.4 -> v0.1.6
    Updating backtrace v0.3.32 -> v0.3.35
    Updating backtrace-sys v0.1.30 -> v0.1.31
      Adding base64 v0.10.1
    Removing blake2-rfc v0.2.18
      Adding blake2b_simd v0.5.7
    Removing build_const v0.2.1
    Updating cargo_metadata v0.8.0 -> v0.8.2
    Updating cc v1.0.37 -> v1.0.41
    Updating constant_time_eq v0.1.3 -> v0.1.4
    Removing crc v1.8.1
    Updating crossbeam-epoch v0.7.1 -> v0.7.2
    Updating crossbeam-utils v0.6.5 -> v0.6.6
    Updating flate2 v1.0.9 -> v1.0.11
    Updating getrandom v0.1.6 -> v0.1.11
    Removing isatty v0.1.9
    Updating lazy_static v1.3.0 -> v1.4.0
    Updating libc v0.2.58 -> v0.2.62
    Updating log v0.4.6 -> v0.4.8
    Updating memchr v2.2.0 -> v2.2.1
    Updating memoffset v0.2.1 -> v0.5.1
    Updating miniz_oxide v0.2.1 -> v0.3.2
    Removing miniz_oxide_c_api v0.2.1
    Removing numtoa v0.1.0
      Adding proc-macro2 v1.0.1
    Removing quote v0.6.12
      Adding quote v0.6.13
      Adding quote v1.0.2
    Updating rand_chacha v0.2.0 -> v0.2.1
    Removing rand_core v0.4.0
    Removing rand_core v0.5.0
      Adding rand_core v0.4.2
      Adding rand_core v0.5.1
    Updating redox_syscall v0.1.54 -> v0.1.56
    Removing redox_termios v0.1.1
    Updating redox_users v0.3.0 -> v0.3.1
    Updating regex v1.1.7 -> v1.2.1
    Updating regex-syntax v0.6.7 -> v0.6.11
      Adding rust-argon2 v0.5.1
    Updating rustc-demangle v0.1.15 -> v0.1.16
      Adding rustc_version v0.2.3
    Removing scoped_threadpool v0.1.9
    Updating scopeguard v0.3.3 -> v1.0.0
    Updating serde v1.0.94 -> v1.0.99
    Updating serde_derive v1.0.94 -> v1.0.99
    Updating slog v2.4.1 -> v2.5.2
    Updating slog-term v2.4.0 -> v2.4.1
    Removing spin v0.5.0
    Removing syn v0.15.39
      Adding syn v0.15.44
      Adding syn v1.0.5
    Removing termion v1.5.3
    Updating toml v0.5.1 -> v0.5.3
    Updating twox-hash v1.4.1 -> v1.5.0
    Updating ucd-util v0.1.3 -> v0.1.5
    Updating unicode-width v0.1.5 -> v0.1.6
      Adding unicode-xid v0.2.0
    Updating utf8-ranges v1.0.3 -> v1.0.4
      Adding wasi v0.5.0
    Updating winapi v0.3.7 -> v0.3.8
```

### CODE REVIEW

**Comment by repi** [comment]
This is a bit of a weird error @Jake-Shadle :

```
tage: license_check

 Aug 29 14:29:19.136 ERRO detected an exception not explicitly allowed, exception: LLVM-exception, crate: wasi@0.5.0

 Aug 29 14:29:19.137 ERRO encountered 1 license errors
```

**Comment by repi** [comment]
Oh I see it is the new `wasi` crate that has a fairly complex license definition `Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT`

**Comment by Jake-Shadle** [comment]
Hah, that is weird, but you can just add `LLVM-exception` to the license allow list, which is what we already have in ark.

**Comment by repi** [comment]
Yes, but we are technically parsing the license wrong right? `Apache-2.0 WITH LLVM-exception` should be one of the detected licenses, not just `LLVM-exception`.

**Comment by Jake-Shadle** [comment]
For simplicity I just consider exceptions in isolation, but maybe that is wrong. It's easy enough to fix!

**Comment by repi** [comment]
Thanks for confirming, I've filed #22 to track that and in this PR will at least temporarily add that exception to the license allow list.

**Pull request merged**
