### PR TITLE
Add support for warn/deny on build.rs and proc-macros

### PR DESCRIPTION
**Pull request by repi**
I did this change a month ago but didn't finish the last parts of it of adding explicit allow lists and documentation. But thought I'd get it up-to-date with the latest changes and have it as a PR.

The general idea around this is that as neither build.rs (custom builds) nor proc macros are sandboxed, and have full system access, there can be use-cases where a project or organization simply do not want to allow them to be used, or at least want to explicitly allow only certain vetted crates builds.

Another use special use case that I've run into was a workspace where we only used very small Rust-only crates under WASM and want to make sure it builds very quickly and with minimal dependencies, and then not allowing custom builds or proc-macros can be a benefit.

This feature as is though, without the support for allow lists, it is a fairly strict and often not too practical lint rule. But it is also quite nice to have for more restricted use cases and to quickly review build.rs files as it gives you quick local links to just jump into the files on the warnings/errors.

But should at least add some docs before we get this in.

## Example: deny build.rs

```toml
[builds]
custom-builds = "deny"
```

image

## Example: warn on proc-macros

```toml
[builds]
proc-macros = "warn"
```

image

### CODE REVIEW

**Comment by Jake-Shadle** [comment]
Yah, I could add allow lists later if you like?

**Comment by repi** [comment]
That would be great! 

Not fully sure which approach is the best, easiest would be list of allowed crate names, with optional version modifiers, similar to the skip lists. That is probably a good start. 

But technically something like the hashed license checks would be safer and better because if one reviews a specific build.rs and allows that, the next crate version could completely change it and should trigger a fail and re-review. But that would have to include not just the hash of the build.rs but all of its build-dependency crates also making it significantly more complicated. So probably a list of allowed crates is easier and a good start, this is a pretty big topic otherwise

**Comment by Jake-Shadle** [comment]
Yah, an allow list to start would be easiest, but of course far from comprehensive.

**Comment by repi** [comment]
Do want to have this, maybe we just merge it in instead and have the basic support @Jake-Shadle ?

**Comment by Jake-Shadle** [comment]
Yah just make a new PR, github wouldn't let me delete the master branch while it was open.

**Comment by Jake-Shadle** [comment]
(and won't let me reopen because master and builds are both gone)

**Comment by repi** [comment]
Ah I think before one delete the branch one can move the PRs to be targeted to the new `main`, but one can't do that now afterwards for some reason, nor re-open it. So one would have to create a new one

**Pull request closed without merging**
