### PR TITLE
Implement standalone feature

### LINKED ISSUE #54: Support for running without cargo.exe installed
Currently as we use `cargo_metadata` crate the user running `cargo-deny` also have to have the  full Cargo toolchain installed, in other words: `cargo-deny` is not a fully standalone executable.

This is ok and good for the default use case as it is very likely a user that is interested in using `cargo-deny` also have Cargo and Rust installed :) 

But for CI and/or minimal docker images it would be nice if we had an optional feature flag for using the `cargo` crate and [`output_metadata`](https://docs.rs/cargo/0.40.0/cargo/ops/fn.output_metadata.html) directly on it instead of invoking `cargo.exe`. Can still take the .json output and feed it into `cargo_metadata` to leave the rest of the code and parsing unchanged.

### PR DESCRIPTION
**Pull request by Stupremee**
This PR introduces the new build feature `standalone`. 
If this feature is enabled, `cargo-deny` doesn't use the `cargo` binary on the system, but the `cargo` crate.

Resolves #54

### CODE REVIEW

**Comment by Jake-Shadle** [comment]
Since this is the first feature for cargo-deny, you should probably modify https://github.com/EmbarkStudios/cargo-deny/blob/main/.github/workflows/ci.yaml#L103 to use the feature so that it gets coverage.

**Comment by repi** [comment]
nice!

For the published binaries of cargo-deny, should we also switch them to use this instead so they don't require Rust & Cargo to be installed? The extra build time for that CI publish step shouldn't be too bad. And then we can simplify the cargo-deny-action to reduce its size as it doesn't need the full Rust environment (tracked in https://github.com/EmbarkStudios/cargo-deny-action/issues/3).

The nice thing about that approach is that users building cargo-deny locally (which obviously have Rust installed) will build and use with that, without having to build the Cargo crate, and same if one does `cargo install cargo-deny` to compile cargo-deny. But the standalone separate binaries are fully standalone

**Comment by Jake-Shadle** [comment]
Yah, that's probably a good idea, though I would need to add a new test to actually run it in an isolated environment, as there might be some dependencies with regards to environment variables being available that won't be set etc.

**Comment by Stupremee** [comment]
I think it's better if you add the changes to the release process, because I have no idea about the CI part

**Review by Jake-Shadle — APPROVED** [review]
Sorry for not merging this sooner, thanks a lot for this change!

**Pull request merged**
